// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeKr9lCbu3AIQwJwGYXYzUC8snJNhGIj0',
    appId: '1:22986435445:web:53dd8ca369d54bd7b0413c',
    messagingSenderId: '22986435445',
    projectId: 'ir-blaster-69342',
    authDomain: 'ir-blaster-69342.firebaseapp.com',
    storageBucket: 'ir-blaster-69342.firebasestorage.app',
    measurementId: 'G-XEDS4G987E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKr9lCbu3AIQwJwGYXYzUC8snJNhGIj0',
    appId: '1:22986435445:android:53dd8ca369d54bd7b0413c',
    messagingSenderId: '22986435445',
    projectId: 'ir-blaster-69342',
    storageBucket: 'ir-blaster-69342.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeKr9lCbu3AIQwJwGYXYzUC8snJNhGIj0',
    appId: '1:22986435445:ios:53dd8ca369d54bd7b0413c',
    messagingSenderId: '22986435445',
    projectId: 'ir-blaster-69342',
    storageBucket: 'ir-blaster-69342.firebasestorage.app',
    iosBundleId: 'com.example.esp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeKr9lCbu3AIQwJwGYXYzUC8snJNhGIj0',
    appId: '1:22986435445:ios:53dd8ca369d54bd7b0413c',
    messagingSenderId: '22986435445',
    projectId: 'ir-blaster-69342',
    storageBucket: 'ir-blaster-69342.firebasestorage.app',
    iosBundleId: 'com.example.esp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeKr9lCbu3AIQwJwGYXYzUC8snJNhGIj0',
    appId: '1:22986435445:web:53dd8ca369d54bd7b0413c',
    messagingSenderId: '22986435445',
    projectId: 'ir-blaster-69342',
    authDomain: 'ir-blaster-69342.firebaseapp.com',
    storageBucket: 'ir-blaster-69342.firebasestorage.app',
    measurementId: 'G-XEDS4G987E',
  );
}
